version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Font
          command: apt-get install -y libfontconfig1
      - run:
          mvn test